//! The built-in web console (notes/REMOTE.md Phase 5): serve the vendored
//! noVNC assets (`novnc/`, embedded at build time by `build.rs`) over plain
//! HTTP on the WebSocket port. `GET /` is EWM's console page, which loads
//! `core/rfb.js` and connects back to the same host and port with a
//! WebSocket upgrade — so one port carries both the page and the RFB stream,
//! the Proxmox shape. Serving is optional (`remote.web` / `--serve …?web=`):
//! without it the WebSocket port answers plain HTTP with `426` as before.
//!
//! This is a static-table file server, not a web server: no filesystem
//! access at runtime, no keep-alive, no ranges — exactly enough to hand a
//! browser ~60 pinned files.

use std::io::{self, Write};

// NOVNC_ASSETS: &[(&str, &[u8])], generated by build.rs from novnc/.
include!(concat!(env!("OUT_DIR"), "/novnc_assets.rs"));

/// Look up an asset by URL path: `/` maps to the console page, the query
/// string is ignored, and anything not literally in the embedded table
/// (there goes `..`) is `None`. Returns `(content_type, bytes)`.
pub fn asset(path: &str) -> Option<(&'static str, &'static [u8])> {
    let path = path.split(['?', '#']).next().unwrap_or(path);
    let key = match path.trim_start_matches('/') {
        "" => "index.html",
        key => key,
    };
    NOVNC_ASSETS
        .iter()
        .find(|(name, _)| *name == key)
        .map(|&(name, bytes)| (content_type(name), bytes))
}

/// The Content-Type for an asset name, by extension. ES modules require a
/// JavaScript MIME type or the browser refuses to import them.
fn content_type(name: &str) -> &'static str {
    match name.rsplit_once('.').map(|(_, ext)| ext) {
        Some("html") => "text/html; charset=utf-8",
        Some("js") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json") => "application/json",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("md") | Some("txt") => "text/plain; charset=utf-8",
        _ => "application/octet-stream",
    }
}

/// Answer one plain-HTTP GET on the WebSocket port: the asset, or a 404.
/// One response per connection (`Connection: close`) — a browser fetches the
/// handful of module files in parallel connections and moves on.
pub fn respond<W: Write>(writer: &mut W, path: &str) -> io::Result<()> {
    match asset(path) {
        Some((content_type, body)) => {
            let header = format!(
                "HTTP/1.1 200 OK\r\n\
                 Content-Type: {content_type}\r\n\
                 Content-Length: {}\r\n\
                 Cache-Control: no-cache\r\n\
                 Connection: close\r\n\r\n",
                body.len()
            );
            writer.write_all(header.as_bytes())?;
            writer.write_all(body)
        }
        None => writer.write_all(
            b"HTTP/1.1 404 Not Found\r\n\
              Content-Type: text/plain\r\n\
              Content-Length: 10\r\n\
              Connection: close\r\n\r\n\
              not found\n",
        ),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn console_page_and_engine_are_embedded() {
        let (content_type, body) = asset("/").expect("console page");
        assert_eq!(content_type, "text/html; charset=utf-8");
        let page = std::str::from_utf8(body).expect("utf-8 page");
        assert!(page.contains("core/rfb.js"), "page loads the noVNC engine");

        let (content_type, body) = asset("/core/rfb.js").expect("noVNC engine");
        assert_eq!(content_type, "text/javascript; charset=utf-8");
        assert!(!body.is_empty());

        // The engine's zlib dependency travels with it (ES module imports).
        assert!(asset("/vendor/pako/lib/zlib/inflate.js").is_some());
        // And the license rides along.
        assert!(asset("/LICENSE.txt").is_some());
    }

    #[test]
    fn lookup_ignores_queries_and_rejects_everything_else() {
        assert!(asset("/?autoconnect=true").is_some(), "query ignored");
        assert!(asset("/index.html").is_some());
        assert!(asset("/nope.js").is_none());
        // No path arithmetic: only literal table entries resolve.
        assert!(asset("/../Cargo.toml").is_none());
        assert!(asset("/core/../../etc/passwd").is_none());
    }

    #[test]
    fn respond_frames_the_asset_and_the_404() {
        let mut out = Vec::new();
        respond(&mut out, "/").expect("respond");
        let text = String::from_utf8_lossy(&out);
        assert!(text.starts_with("HTTP/1.1 200 OK\r\n"), "{text}");
        assert!(text.contains("Content-Type: text/html"), "{text}");

        let mut out = Vec::new();
        respond(&mut out, "/missing").expect("respond");
        assert!(String::from_utf8_lossy(&out).starts_with("HTTP/1.1 404"));
    }
}
